# Generated by Django 2.2 on 2020-11-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numero_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('numero_usina', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cliente')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usina')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usinas',
            field=models.ManyToManyField(related_name='usinas', through='web.Participacao', to='web.Usina'),
        ),
    ]
